apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: demo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: petclinic
          image: 713332525966.dkr.ecr.ap-south-1.amazonaws.com/petclinic:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
